export const classNames = {
    main: "flex min-h-screen flex-col items-center justify-between p-2",
    mainNoPadding: "flex min-h-screen max-h-screen flex-col items-center justify-between",
    navbar: "flex w-full h-20 bg-emerald-800 sticky",
    navbarElementsContainer: "flex gap-x-6 text-white",
    heightFullContainer: "container mx-auto px-4 h-full",
    widthFull: "w-full",
    containerFlex: "flex items-center",
    containerFlexHeightFull: "flex justify-between items-center h-full",
    containerFlexCenter:"flex min-h-screen items-center",
    content:"flex min-h-screen items-center justify-between",
    justifyBetween: "flex flex-col items-center justify-between",
    fixedTop: "fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30",
    fixedTopNoPadding: "fixed left-0 top-0 flex w-full justify-center lg:static ",
    notFixed: "flex w-full items-center",
    fixedBottom: "fixed left-0 bottom-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30",
    fixedBottomCenterNotStatic: "fixed bottom-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30",
}